### ISSUE TITLE
how can I get roboflow.zip？

### ISSUE THREAD

**Issue by LingjieBao1998** [shashank524/patent_analysis#1]
I run this code 
"""
!curl -L "https://app.roboflow.com/ds/q91Y8tjqmp?key=XdXSj52rf1" > roboflow.zip; unzip roboflow.zip; rm roboflow.zip
"""
, but it return that
![image](https://github.com/shashank524/patent_analysis/assets/62501004/173d1762-74cc-44db-97bf-c7a446468548).
It may be inaccessible for this datasets

**Comment by shashank524** [comment]
Thanks for reporting the issue. When exporting your dataset on Roboflow, instead of selecting "Terminal," choose "Jupyter" and try that code.
